aliyun:
    oss:
      # oss对外服务的访问域名
      endpoint: xxxxxxxxxxxxx
      # 访问身份验证中用到用户标识
      accessKeyId: xxxxxxxxxx
      # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
      accessKeySecret: xxxxxxxxxxxxx
      # oss的存储空间
      bucketName: xxxxxx
      # 有效时间
      expirationTime: 3600000